### ISSUE TITLE
Trying to create StockChart

### ISSUE THREAD

**Issue by gubenkovalik** [cebor/angular-highcharts#134]
I have Angular 5.
In my component i import 

`import {Chart, StockChart, HIGHCHARTS_MODULES} from "angular-highcharts";`
then i init chart like this

```
this.chart = new StockChart({
            // chart: {
            //     type: 'spline'
            // },
            xAxis: {
                type: 'datetime',
                dateTimeLabelFormats: { // don't display the dummy year
                    month: '%e. %b',
                    year: '%b'
                },
                title: {
                    text: 'Date'
                }
            },
            yAxis: {
                title: {
                    text: 'USD'
                },
            },
            tooltip: {
                headerFormat: '<b>{series.name}</b><br>',
                pointFormat: '${point.y:.2f}/ETH'
            },
            plotOptions: {
                spline: {
                    marker: {
                        enabled: true
                    }
                }
            },

            title: {
                text: 'Ethereum price history'
            },
            credits: {
                enabled: false
            },
            series: this.data
        });
```

And after compile , in browser console i see error:
`TypeError: __WEBPACK_IMPORTED_MODULE_0_highcharts__.stockChart is not a function`

What am I doing wrong?

**Comment by k1ng440** [comment]
any update on this please?

**Comment by iturn** [comment]
Seems like you missed a part in the documentation. You must import the additional modules like stock in app.module.ts like so
`
import { HIGHCHARTS_MODULES } from 'angular-highcharts';
import highstock from 'highcharts/modules/stock.src';
export function highchartsModules() {
    return [ highstock ];
}

export function highchartsModules() {
  return [ more, exporting ];
}

@NgModule({
  providers: [
    { provide: HIGHCHARTS_MODULES, useFactory: highchartsModules }
  ]
})
export class AppModule { }`

then in the module of your component that has the chart, for example shared.module.ts, import Chartmodule

**Comment by cebor** [comment]
What is missing in the docs: https://github.com/cebor/angular-highcharts#highstock--highmaps-support.

I will add it.

**Comment by iturn** [comment]
It doesnt seem like documentation is missing, i meant to say that Guben missed reading a part of it.
Its all well documented, thanks @cebor for that 👍

**Comment by cebor** [comment]
Oh, i cant read ^^

**Comment by yash27** [comment]
@gubenkovalik  To use Stock Chart, you need to downgrade your CLI version to 1.6.1 if you are using higher version. Stock chart will not work in CLI version 1.6.2+ .

**Comment by iturn** [comment]
Im not sure this is the case since I'm using stock and latest cli

**Comment by nadeem-shaikh** [comment]
@iturn @yash27 

can you guys do ng -v and paste the output here. 

I am not able to get it working with below config.
Angular CLI: 1.6.7
Node: 8.10.0
OS: win32 x64
Angular: 5.1.2
... common, compiler, core, platform-browser
... platform-browser-dynamic

angular/animations: 5.2.9
angular/cli: 1.6.7
angular/compiler-cli: 5.2.9
angular/forms: 5.2.9
angular/http: 5.2.9
angular/language-service: 5.2.9
angular/router: 5.2.9
angular-devkit/build-optimizer: 0.0.42
angular-devkit/core: 0.0.29
angular-devkit/schematics: 0.0.52
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.7
schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

**Comment by amandainnis** [comment]
my group is using the cli in 1.7.4, i can't change cli versions to get this to work.  can you help for stockchart in this version?

**Comment by cebor** [comment]
@amandainnis for angular5 install `angular-highcharts@5` 

```sh
npm i angular-highcharts@5
```

**Comment by amandainnis** [comment]
//app module
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { ChartModule, HIGHCHARTS_MODULES  } from 'angular-highcharts';
import { StockchartComponent } from './stockchart/stockchart.component';
import * as highstock from 'highcharts/modules/stock.src';

export function highchartsModules() {
  return [ highstock ];
  }

@NgModule({
  declarations: [
    AppComponent,
    StockchartComponent,
    ChartModule
  ],
  imports: [
    BrowserModule
  ],
  providers: [{
    provide: HIGHCHARTS_MODULES,
    useFactory: highchartsModules
  }],
  bootstrap: [AppComponent]
})
export class AppModule { }

//my-component.component.ts
import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';
import { StockChart } from 'angular-highcharts';


@Component({
  selector: 'app-stockchart',
  templateUrl: './stockchart.component.html',
  styleUrls: ['./stockchart.component.scss']
})
export class StockchartComponent implements OnInit {

  // Highcharts.setOptions({ lang: { rangeSelectorZoom: , "": , } }: {
  //   lang: {
  //       rangeSelectorZoom: any;
  //       : any;
  //   };
  // }): any

  theme: any;
  chart = new StockChart({
    chart: {
      type: 'line'
    },
    title: {
      text: 'Linechart'
    },
    credits: {
      enabled: false
    },
    series: [
      {
        name: 'Line 1',
        data: [1, 2, 3]
      }
    ]
  });
  constructor() { }
  ngOnInit() {   
  }
}


//component.html
<div [chart]="chart"></div>

//tsconfig.app.json
..
,
    "types": [ "highcharts"]
..


i'm still getting no chart displayed.  what am i doing wrong?

**Comment by cebor** [comment]
@amandainnis please create a stackblitz to reproduce this issue.

And keep in mind to set dependency versions correctly

Example: https://stackblitz.com/edit/angular-9nkrgd

**Comment by amandainnis** [comment]
I figured out that the ChartModule needed to be an import in the AppModule, not a declaration.

**Comment by amandainnis** [comment]
the reason i switched to your version instead of angular2-highcharts is that i'm trying to access the static properties of highcharts and utilize the "setOptions" feature.  if you have any pointers on that, I would really appreciate it

**Comment by cebor** [comment]
@amandainnis 

```ts
import { Highcharts } from 'angular-highcharts';

Highcharts.setOptions()
```

**Comment by amandainnis** [comment]
this still did not work

**Comment by amandainnis** [comment]
this still did not work

**Comment by cebor** [comment]
Do you have some errors or examples for me to reproduce this issue?

**Comment by amandainnis** [comment]
Highcharts.setOptions({
    lang: { 
    rangeSelectorZoom: '' }
});
this is intended to remove the text 'zoom' from highstock range buttons.  It works on jsfiddle with regular javascript.  

When this script is placed above the @component, what is inside the setOptions produces errors saying it is not part of the object literal

**Comment by yash27** [comment]
@amandainnis many of the features/properties of highcharts are not present inside the object literal. That is loaded after the angular completely loads all the view components.
