### ISSUE TITLE
TypeError: chartModule is not a function

### ISSUE THREAD

**Issue by olchaeng** [cebor/angular-highcharts#112]
Hi.

I have a problem using angular-highcharts-stockchart.

I paste example code in my code. 

But it occurs an error.

**in Chrome console :**

```
TypeError: chartModule is not a function
    at eval (angular-highcharts.es5.js:245)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (angular-highcharts.es5.js:244)
    at new ChartModule (angular-highcharts.es5.js:274)
    at _createClass (core.js:10915)
    at _createProviderInstance$1 (core.js:10889)
    at initNgModule (core.js:10842)
    at new NgModuleRef_ (core.js:12096)
    at createNgModuleRef (core.js:12086)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14430)
```

Below that is my code snippet.

**app.module.ts :**

```
...
import {ChartModule, HIGHCHARTS_MODULES} from 'angular-highcharts';
import highstock from 'highcharts/modules/stock.src';
import exporting from 'highcharts/modules/exporting.src';

export function highchartsModules() {
  // apply Highstock Modules to this array
  return [highstock, exporting];
}
...

@NgModule({
  declarations: [
    AppComponent,
    SigninComponent,
    StrategyListComponent,
    StrategyDetailComponent,
    StrategyComponent
  ],
  imports: [
    ...
  ],
  providers: [
    ...
    {provide: HIGHCHARTS_MODULES, useFactory: highchartsModules}
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**package.json :**

```
...
 "@angular/cdk": "^5.0.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-highcharts": "^5.2.0",
    "core-js": "^2.4.1",
    "highcharts": "^6.0.4",
...

```

**Comment by cebor** [comment]
@olchaeng 

I have created a working example for you: https://stackblitz.com/edit/angular-uwxsas

Maybe this helps ...

**Comment by olchaeng** [comment]
@cebor Thank you.

I solved the problem. 

The reason is angular/cli version.

I fix @angular/cli version 1.6.2 to 1.6.2 in package.json file. -> npm install -> ng serve -> It works!

I don't know why is works.

anyone know why is?

**Comment by jliang6** [comment]
I have the same problem with angular/cli@1.6.2.  Once I revert back to angular/cli@1.6.1, everything works fine.

**Comment by attilacsanyi** [comment]
Same error with `angular-highcharts` and `@angular/cli v1.6.3`.

Only works with `@angular/cli v1.6.1`.

Hopefully will be fixed soon. Thanks @cebor

**Comment by cebor** [comment]
Hey all, `--prod` build should work even with ng-cli `1.6.3`.

Don't know why normal build is failing, i will let you hear if i find it out.

**Comment by cebor** [comment]
I created an issue: https://github.com/angular/angular-cli/issues/9058

**Comment by cebor** [comment]
Here is a temporary workaround to fix this issue: https://github.com/angular/angular-cli/issues/9058#issuecomment-355021360

**Comment by moepkid** [comment]
@cebor How can we use this fix when we import the module? 

```
import * as ChartModule from 'angular-highcharts'

import({
  ChartModule
})
```

does not work.

**Comment by cebor** [comment]
@moepkid you don't have to force the import for `ChartModule`.

**Comment by rhdlmv** [comment]
I get error when  I revert back to angular/cli@1.6.1:

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\paul\Desktop\angular-highcharts-stock\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

I found a solution through from
https://github.com/angular/angular-cli/issues/9307

But I get error again:

TypeError: chartModule is not a function
    at eval (angular-highcharts.es5.js:270)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (angular-highcharts.es5.js:269)
    at new ChartModule (angular-highcharts.es5.js:291)
    at _createClass (core.js:10884)
    at _createProviderInstance$1 (core.js:10858)
    at initNgModule (core.js:10811)
    at new NgModuleRef_ (core.js:12066)
    at createNgModuleRef (core.js:12055)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14389)


package.json :
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-highcharts": "^5.2.0",
    "core-js": "^2.4.1",
    "highcharts": "^6.0.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.0",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/highcharts": "^5.0.16",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

Anyone know why is?

**Comment by joeykruger** [comment]
I have the same issue.  I've tried everything, including rolling back angular/cli to version 1.6.1, but cannot get this working.   Will check back over next few days\weeks though.  

If anyone has a solution or workaround, please share!

**Comment by ubirajr** [comment]
Same issue here.

`Unhandled Promise rejection: chartModule is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: chartModule is not a function
    at eval (angular-highcharts.es5.js:293)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (angular-highcharts.es5.js:292)
    at new ChartModule (angular-highcharts.es5.js:314)
    at _createClass (core.js:10884)
    at _createProviderInstance$1 (core.js:10858)
    at initNgModule (core.js:10811)
    at new NgModuleRef_ (core.js:12066)
    at createNgModuleRef (core.js:12055)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14389) TypeError: chartModule is not a function
    at eval (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:305:13)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:304:27)
    at new ChartModule (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:326:17)
    at _createClass (webpack-internal:///../../../core/esm5/core.js:11098:20)
    at _createProviderInstance$1 (webpack-internal:///../../../core/esm5/core.js:11072:26)
    at initNgModule (webpack-internal:///../../../core/esm5/core.js:11025:28)
    at new NgModuleRef_ (webpack-internal:///../../../core/esm5/core.js:12280:9)
    at createNgModuleRef (webpack-internal:///../../../core/esm5/core.js:12269:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (webpack-internal:///../../../core/esm5/core.js:14603:12)`

Please, can anyone shed a light on this?

**Comment by inyono** [comment]
@joeykruger @ubirajr The workaround (as mentioned in https://github.com/angular/angular-cli/issues/9058#issuecomment-355021360) is to force the default import for your chart module imports. So do
```.js
import * as sunburst from 'highcharts/modules/sunburst.src';
```
instead of
```.js
import sunburst from 'highcharts/modules/sunburst.src';
```
for all your chart modules.

**Comment by gubenkovalik** [comment]
can it be fixed? or any workaround?

**Comment by cebor** [comment]
@gubenkovalik can you read :D ?

**Comment by gubenkovalik** [comment]
i still dont see any working solution

**Comment by SayakMukhopadhyay** [comment]
@gubenkovalik This https://github.com/cebor/angular-highcharts/issues/112#issuecomment-364705934

**Comment by ubirajr** [comment]
It worked for me after all. Seems it had a conflict with angular/compiler-cli. Once I downgraded it to 5.0.0 it worked.

Ubirajara Moraes

**Comment by superkick** [comment]
I tried the above solutions(including direct importing and downgrading) but none worked for me.

I also used the demo project component in my application and had the same error.

Currently using versions:

Angular CLI: 1.7.1
Node: 6.11.3
OS: darwin x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

angular/cli: 1.7.1
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.3.2
angular-devkit/schematics: 0.3.2
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.10.1
schematics/angular: 0.3.2
schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0

Any suggestions on how to continue would be greatly appreciated.

**Comment by attilacsanyi** [comment]
Dear @superkick I just upgraded to the latest cli (1.7.1) and angular (5.2.6) and the custom `HighchartsModule` still working fine for me:

```
import { NgModule } from '@angular/core';
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';

import * as Highcharts from 'highcharts';
import * as boostCanvas from 'highcharts/modules/boost-canvas';
import * as boost from 'highcharts/modules/boost.src';
import * as exporting from 'highcharts/modules/exporting.src';
import * as heatmap from 'highcharts/modules/heatmap.src.js';
import * as noDataToDisplay from 'highcharts/modules/no-data-to-display.src';
import * as offlineExporting from 'highcharts/modules/offline-exporting.src';

@NgModule({
  exports: [ChartModule],
  providers: [
    {
      provide: HIGHCHARTS_MODULES,
      useFactory: () => [
        boostCanvas, boost, exporting, heatmap, noDataToDisplay, offlineExporting
      ]
    }
  ]
})
export class HighchartsModule {
  constructor() {
    const globalOptions: Highcharts.GlobalObject = {
      // http://api.highcharts.com/highstock/global.timezoneOffset
      timezoneOffset: new Date().getTimezoneOffset()
    };

    Highcharts.setOptions({
      global: globalOptions
    });
  }
}
```

I hope this helps ;-)

**Comment by cebor** [comment]
Good News, the commit which fixes this issue is in: https://github.com/angular/angular-cli/commit/605e4feab663d0e5c08a333ee3909047ccab2ce0.

So this issue should gone away with the next angular-cli release.

**Comment by attilacsanyi** [comment]
Thanks @cebor for the update thats really a great news!

BTW, I use this code for more than a month with `--prod` and working well.
Proof:
![image](https://user-images.githubusercontent.com/2144794/36671750-2a817d02-1afd-11e8-84a7-8d145507e375.png)
[Source](https://angularplaybook.com/courses/285976/lectures/4404784) from **angularplaybook** of Justin Schwartzenberger who is a product manager and educator at Nrwl.io.

**Comment by superkick** [comment]
hey @attilacsanyi,  

many thanks for your help!  

i can confirm this approach is working correctly for me.

@cebor - excellent news! keep up the great work  👍

**Comment by nadeem-shaikh** [comment]
I am still getting the error.

Angular CLI: 1.7.3
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by inyono** [comment]
@nadeem-shaikh Did you try the workaround mentioned in https://github.com/cebor/angular-highcharts/issues/112#issuecomment-364705934 ?

**Comment by manhar-developer** [comment]
Hi All , I am getting following Error : 
Angular Configuration : Angular CLI: 1.7.3
Node: 8.11.1
OS: win32 x64
Angular: 5.2.9


TypeError: chartModule is not a function
    at eval (webpack-internal:///./node_modules/angular-highcharts/angular-highcharts.es5.js:297)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (webpack-internal:///./node_modules/angular-highcharts/angular-highcharts.es5.js:296)
    at new ChartModule (webpack-internal:///./node_modules/angular-highcharts/angular-highcharts.es5.js:318)


app.module.ts code : 


import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {ChartModule , HIGHCHARTS_MODULES} from 'angular-highcharts';

import more from 'highcharts/highcharts-more.src';
import exporting from 'highcharts/modules/exporting.src.js';

import { AppComponent } from './app.component';
import { LineChartComponent } from './components/line-chart/line-chart.component';
import Drilldown from 'highcharts/modules/drilldown.js';
export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ more, exporting, Drilldown ];
}

@NgModule({
  declarations: [
    AppComponent,
    LineChartComponent
  ],
  imports: [
    BrowserModule, ChartModule
  ],
  providers: [{provide: HIGHCHARTS_MODULES, useFactory: highchartsModules}],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by attilacsanyi** [comment]
Dear @manhar-developer I think you should also include `drilldown` module in the same manner like `exporting` module so:

`import Drilldown from 'highcharts/modules/drilldown.src.js';` (instead of just drilldown.js)

The reason because of the [docs](https://github.com/cebor/angular-highcharts#using-highcharts-modules)

Let us know if this helps.

**Comment by manhar-developer** [comment]
Hi @attilacsanyi 
I tried  inclusing Drilldown like this : import Drilldown from 'highcharts/modules/drilldown.src.js'; 
Still I am getting "chartModule is not a function"

When I use providers like providers: [{provide: HIGHCHARTS_MODULES, useFactory: highchartsModules}], I got this error

**Comment by manhar-developer** [comment]
Yes Please. I tried to downgrade to angular 5.0.0 as well still not success. 
Struggling for this. Please look at the repo 
https://github.com/manhar-developer/angularwidCharts.git

**Comment by manhar-developer** [comment]
@attilacsanyi 
Tried providers: [
{provide: HIGHCHARTS_MODULES,
    useFactory: () => [drilldown]
}],
Its working :). Appreciate your help 👍 Thanks.

**Comment by attilacsanyi** [comment]
Dear @manhar-developer I am not saying its impossible, but never did something similar so far.
I just played with point select and zoom on an individual chart. I guess you need to find first how to trigger the drill down from code then call it once the another chart was interacted.

_BTW, not the right place to discuss this :P Sorry @cebor_

**Comment by manvfx** [comment]
I have no fault, my problem is in map display. I have done all the essentials. But the map is not displayed. This problem is important to me. Help me please

**Comment by manvfx** [comment]
https://stackblitz.com/edit/angular-rwkuh4

**Comment by manvfx** [comment]
I need a sample map code with Angular

**Comment by cebor** [comment]
@manvfx on stackblitz you have to import the highcharts modules without `* as`.

**Comment by manvfx** [comment]
i write 
```
import highcharts from 'highcharts';
```
but not working

**Comment by cebor** [comment]
@manvfx not highcharts itself, only the modules. But when you using the cli, all should work.

You can also use the new cli rc which should solve all this issues.

**Comment by ariklu** [comment]
example published on [https://stackblitz.com/edit/angular-highcharts-stock?file=.angular-cli.json]
is not working for me 
Chrome : TypeError: chartModule is not a function
    at eval (angular-highcharts.es5.js:325)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (angular-highcharts.es5.js:324)
    at new ChartModule (angular-highcharts.es5.js:346)
    at _createClass (core.js:10933)
    at _createProviderInstance$1 (core.js:10907)
    at initNgModule (core.js:10860)
    at new NgModuleRef_ (core.js:12115)
    at createNgModuleRef (core.js:12104)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:14438)

package.json
"dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@angular/router": "5.2.10",
    "angular-highcharts": "^5.2.12",
    "core-js": "^2.4.1",
    "highcharts": "^6.1.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.1",
    "@angular/compiler-cli": "5.2.10",
    "@angular/language-service": "5.2.10",
    "@types/highcharts": "^5.0.22",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"

**Comment by cebor** [comment]
Issue is fixed with @angular/cli@6.0.0.

**Comment by renukaamujuru** [comment]
i have to implement highmaps in angular 6 but it showing errors.
how to load world.js data in ts file into the map , it showing errors while importing 
the code i want to execute is fro this below link:--
https://www.highcharts.com/maps/demo/doubleclickzoomto
my ts file:--
--------------------------
import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';
import * as HC_map from 'highcharts/modules/map';
HC_map(Highcharts);
import * as $ from 'jquery';;
import * as HC_data from 'highcharts/modules/data.js';
HC_data(Highcharts);
// import * as HC_exporting  from 'highcharts/modules/exporting.js';
// HC_exporting (Highcharts);
// import * as Custom_World from 'highcharts/mapdata/custom/world.js';
// Custom_World(Highcharts);
@Component({
    selector: 'app-highmapchart',
    templateUrl: './highmapchart.component.html',
    styleUrls: ['./highmapchart.component.scss']
})
export class HighmapchartComponent implements OnInit {

    constructor() {
        this.loadScripts();
        this.start();
     }
    loadScripts() {
        const dynamicScripts = [
            'https://code.jquery.com/jquery-3.1.1.min.js',
            'https://code.highcharts.com/maps/highmaps.js',
            'https://code.highcharts.com/maps/modules/data.js',
            'https://code.highcharts.com/maps/modules/offline-exporting.js',
            'https://code.highcharts.com/mapdata/custom/world.js'
        ];
        for (let i = 0; i < dynamicScripts.length; i++) {
          const node = document.createElement('script');
          node.src = dynamicScripts[i];
          node.type = 'text/javascript';
          node.async = false;
          node.charset = 'utf-8';
          document.getElementsByTagName('head')[0].appendChild(node);
        }
      }
      start(){
        $(function () {
        
            $.getJSON('https://cdn.rawgit.com/highcharts/highcharts/680f5d50a47e90f53d814b53f80ce1850b9060c0/samples/data/world-population-density.json', function (data) {

                // Prevent logarithmic errors in color calulcation
                $.each(data, function () {
                    this.value = (this.value < 1 ? 1 : this.value);
                });
            
                // Initiate the chart
                Highcharts.mapChart('container', {
                    chart: {
                        map: 'custom/world'
                    },
            
                    title: {
                        text: ''
                    },
            
                    mapNavigation: {
                        enabled: true,
                        enableDoubleClickZoomTo: true
                    },
            
                    colorAxis: {
                        min: 1,
                        max: 1000,
                        type: 'logarithmic'
                    },
            
                    series: [{
                        data: data,
                        mapData: Highcharts.maps["custom/world"],
                        joinBy: ['iso-a3', 'code3'],
                        name: 'Population density',
                        states: {
                            hover: {
                                color: '#a4edba'
                            }
                        },
                        tooltip: {
                            valueSuffix: '/km²'
                        }
                    }]
                });
            });
        });
    }
    ngOnInit() {

    }

} 
zone.js:192 Uncaught TypeError: Cannot read property '0' of undefined
    at map.js:10
    at Array.forEach (<anonymous>)
    at a.each (highcharts.js:28)
    at G.<anonymous> (map.js:9)
    at highcharts.js:31
    at Array.forEach (<anonymous>)
    at Object.a.each (highcharts.js:28)
    at a.fireEvent (highcharts.js:30)
    at G.getSeriesExtremes (highcharts.js:128)
    at G.setScale (highcharts.js:146)

**Comment by attilacsanyi** [comment]
Consider to use officially supported https://github.com/highcharts/highcharts-angular library instead.
I just found one week ago, so I plan to migrate in the future. @cebor what do you think? Are you going to support this beside the official wrapper? Thanks for your help.

**Comment by renukaamujuru** [comment]
can i have a example of how to import highmaps and use world.js map in angular 5

**Comment by gubenkovalik** [comment]
Fuck this shit, how to stop receiving this fucking excrements?


пн, 6 авг. 2018 г., 8:51 renukaamujuru <notifications@github.com>:

**Comment by cebor** [comment]
Try this:

![screen shot 2018-08-06 at 15 39 06](https://user-images.githubusercontent.com/1576120/43719791-f580d132-998e-11e8-855d-e201b3298024.png)

**Comment by cebor** [comment]
@gubenkovalik try the this:

![screen shot 2018-08-06 at 15 39 06](https://user-images.githubusercontent.com/1576120/43719815-0d48d79c-998f-11e8-8bf0-48c044231cf4.png)

**Comment by regahruzty** [comment]
@cebor please help

package.json :
"dependencies": {
    "@angular/animations": "^7.2.3",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/forms": "^7.2.3",
    "@angular/platform-browser": "^7.2.3",
    "@angular/platform-browser-dynamic": "^7.2.3",
    "@angular/router": "^7.2.3",
    "@coreui/angular": "^2.3.0",
    "@coreui/coreui": "^2.1.6",
    "@ng-select/ng-select": "^2.15.2",
    "@types/datatables.net": "^1.10.14",
    "@types/jquery": "^3.3.29",
    "@types/moment": "^2.13.0",
    "angular-datatables": "^7.0.0",
    "angular-highcharts": "^7.1.0",
    "angular-resizable-element": "^3.2.3",
    "core-js": "^2.6.3",
    "datatables.net": "^1.10.19",
    "datatables.net-buttons-dt": "^1.5.4",
    "datatables.net-dt": "^1.10.19",
    "flag-icon-css": "^3.2.1",
    "font-awesome": "^4.7.0",
    "highcharts": "^7.0.3",
    "jquery": "^3.3.1",
    "jszip": "^3.1.5",
    "moment": "^2.24.0",
    "moment-range": "^4.0.1",
    "ngx-bootstrap": "^3.2.0",
    "ngx-moment": "^3.3.0",
    "ngx-perfect-scrollbar": "^7.2.0",
    "ngx-toastr": "^9.1.1",
    "popper.js": "^1.14.7",
    "rxjs": "~6.3.3",
    "simple-line-icons": "^2.4.1",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular/cli": "^7.2.4",
    "@angular/compiler-cli": "^7.2.3",
    "@angular/language-service": "^7.2.3",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
 
module.ts:
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import * as gantt from 'highcharts/highcharts-gantt.src.js';
import * as exporting from 'highcharts/modules/exporting.src.js';

export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [gantt, exporting];
}

--

providers: [
    { provide: HIGHCHARTS_MODULES, useFactory: highchartsModules }
  ]

--

errors :
ERROR Error: Uncaught (in promise): TypeError: chartModule is not a function
TypeError: chartModule is not a function
    at angular-highcharts.js:392
    at Array.forEach (<anonymous>)
    at ChartService.push../node_modules/angular-highcharts/fesm5/angular-highcharts.js.ChartService.initModules (angular-highcharts.js:391)
    at new ChartModule (angular-highcharts.js:413)
    at _createClass (core.js:21164)
    at _createProviderInstance (core.js:21136)
    at initNgModule (core.js:21069)
    at new NgModuleRef_ (core.js:21796)
    at createNgModuleRef (core.js:21785)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:23616)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17279)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)

**Comment by cebor** [comment]
@regahruzty i think the problem is with gnatt, it looks like it has its own constructor, which is not implemented in this library.
